name: CI
on:
  workflow_dispatch:
    inputs:
      test:
        default: ABC def ghi
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: test
        run: |
          for item in ${{ inputs.test }}
          do
            echo "item=${item}" >> $GITHUB_ENV
            hello ${{ env.item }}
          done
          
