name: CI
on:
  workflow_dispatch:
    inputs:
      test:
        default: ABC def ghi
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: test
        run: |
          task_number=1
          for PATTERN in ${{inputs.test}}
          do
            echo "Item: $PATTERN"
            echo $task_number
            touch "$PATTERN"
            ((task_number++))
          done
          
