name: CI
on:
  workflow_dispatch:
    inputs:
      major:
        type: text
      minor:
        type: text
      batch:
        type: text
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.batch }}
          generate_release_notes: true
          draft: false
          prerelease: false
      - name: Create version branch
        run: |
          git checkout -b v${{ inputs.major }}.${{ inputs.minor }}.x
          git push origin v${{ inputs.major }}.${{ inputs.minor }}.x
