name: CI
on:
  workflow_dispatch:
    inputs:
      test:
        default: ABC def ghi
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: test
        run: |
          for i in {1..5}
          do
            touch $i.txt
          done
          
